const beer = [
    {
      id: 1,
      title: "pilsner",
      category: "light",
      img: "./img/beer1.jpeg",
      desc: `Seu aroma e sabor são acentuados pelo lúpulo, por isso um leve amargor. São claras, com baixo corpo e fácil de beber. Seu processo de produção apresenta uma baixa fermentação e ela também tem um baixo teor alcoólico e com um final seco`,
    },
    {
      id: 2,
      title: "munich dunkel",
      category: "dark",
      img: "./img/beer2.jpeg",
      desc: `Considerada a original Dark Lager da Europa e curiosamente Dunkel quer dizer escuro em alemão. É uma cerveja de baixa fermentação e coloração marrom escura. Seu malte Munich dá a ela um doce amargor e notas de chocolate, caramelo e nozes`,
    },    
    {
      id: 3,
      title: "tradicional bock",
      category: "bock",
      img: "./img/beer3.jpeg",
      desc: `Em seu aroma o malte é moderadamente percebido como pão, já o lúpulo é quase não perceptível e também está em menor evidência no sabor da cerveja, o suficiente para equilibrar com o malte. Sua cor se varia entre o cobre claro ou um marrom consistente.`,
    },    
    {
      id: 4,
      title: "dortmunder export",
      category: "light",
      img: "./img/beer4.jpeg",
      desc: `Também produzida e muito consumida na Alemanha, mas na região de Dortmund. Seu malte e lúpulo são equilibrados, trazendo uma sensação adocicada do malte e também um forte amargor, diferente das Lagers consumidas normalmente.`,
    },
    {
      id: 5,
      title: "helles",
      category: "light",
      img: "./img/beer5.jpeg",
      desc: `Cerveja produzida e consumida em larga escala na região da Alemanha. É considerada uma cerveja com destaque em seu malte e com menos lúpulo no preparo,trazendo pouco amargor. Seu malte dá um sabor de pão e biscoitos, e curiosamente consumida em alguns cafés da manhã na Alemanha`,
    },
    {
      id: 6,
      title: "dark american",
      category: "dark",
      img: "./img/beer6.jpeg",
      desc: `São cervejas escuras escuras, tem baixo corpo, boa carbonatação, espuma (tende para a cor dourada) e também são muito refrescantes. Seu aroma quase não aparece na cerveja, sendo difícil notar o malte ou lúpulo nela. Já a cor varia entre âmbar e marrom escuro`,
    },
    {
      id: 7,
      title: "american lager",
      category: "light",
      img: "./img/beer7.jpeg",
      desc: `Fácil de beber, pouco amargor, final relativamente seco, aroma suave de cereais, cor dourada e cristalina.`,
    },
    {
      id: 8,
      title: "malzbier",
      category: "dark",
      img: "./img/beer8.jpeg",
      desc: `Talvez a mais famosa Dark Lager encontrada no Brasil, já foi mais consumida do que é hoje, mas ainda assim é produzida por grandes cervejarias. Escura e doce, teor alcoólico baixo, após a fermentação é acrescentado xarope de açúcar e caramelo.`,
    },
    {
      id: 9,
      title: "schwarzbier",
      category: "dark",
      img: "./img/beer9.jpeg",
      desc: `É uma cerveja realmente preta, mais escura até que a Munich Dunkel. O aroma que prevalece é o do malte mais moderadamente. Pode ser notado notas de caramelo, café ou chocolate, mas é importante saber que o doce sentido na cerveja é baixo, por isso não deve ser confundida com o estilo Malzbier.`,
    },
    {
      id: 10,
      title: "premium",
      category: "light",
      img: "./img/beer10.jpeg",
      desc: `Um outro estilo americano que se assemelha ao American Lager, mas possuem mais lúpulo e mais malte se tomarmos a American Lager como objeto de comparação, mas já com os outros estilos possui menos malte e pouco aroma  de lúpulo. E sua cor beira o dourado, uma cerveja com um corpo médio`,
    },
    {
        id: 11,
        title: "doppelbock",
        category: "bock",
        img: "./img/beer11.jpeg",
        desc: `É mais forte que a Dunkless Bock e seu teor alcoólico pode variar entre 7% – 10%. Sua coloração ganha destaque, pois podemos ver versões que variam da âmbar até um vermelho rubi, dando uma grande beleza somada ao colarinho cremoso da cerveja.`,
    },
    {
        id: 12,
        title: "helles bock",
        category: "bock",
        img: "./img/beer12.jpeg",
        desc: `Sua cor vai do dourado até o âmbar e o seu aroma de moderado até intenso se tratando do malte da cerveja, com muito pouco ou nada de lúpulo perceptível. Já o sabor podemos perceber que as características do malte europeu predominam — principalmente as notas de malte tostado`,
    },
    {
        id: 13,
        title: "vienna",
        category: "european-lager",
        img: "./img/beer13.jpeg",
        desc: `A versão americana é mais amarga e fortes, enquanto as produzidas na Europa tendem a ser adocicadas.Sua aparência varia entre âmbar e cobre claro, já seu aroma é leve e com poucas características do lúpulo e sutileza do malte`,
    },
    {
        id: 14,
        title: "marzen lager",
        category:"european-lager",
        img: "./img/beer14.jpeg",
        desc: `Apresenta um teor alcoólico um pouco mais alto e a coloração varia entre âmbar e marrom. Seu aroma é bem leve e conseguimos sentir notas de pão tostado e também um pouco de lúpulo, já seu sabor é levemente adocicado e é possível perceber um pouco de caramelo.`,
    },
      
  ];
